#!/bin/bash
# This script creates symlinks from the home directory to any desired dotfiles 
# in ~/.dotfiles

########## Variables
dir=$(dirname $0)
if [ $dir = '.' ]; then
    dir=$(pwd)
fi
olddir=~/.dotfiles_old # old dotfiles backup directory
files="bash_profile bashrc bash_aliases inputrc ctags gitconfig ghci tmux tmux.conf minttyrc config/fish/config.fish config/fish/functions"
##########

# create dotfiles_old in homedir
mkdir -p $olddir

# move any existing dotfiles in homedir to dotfiles_old directory, then create 
# symlinks from the homedir to any files in the ~/.dotfiles directory specified 
# in $files
echo "Moving any existing dotfiles from ~ to $olddir"
for file in $files; do
    if [[ -e ~/.$file ]];then
        mv ~/.$file $olddir
    fi
done

for file in $files; do
    echo "Creating symlink ~/.$file to $dir/home/$file"
    ln -s $dir/home/$file ~/.$file
done
