#!/usr/bin/env bash

packages=(
    "fish"
    "man-db"
    "git" "ssh-tools"
    "neovim" "diffutils" "ripgrep"
    "cowsay" "fortune-mod" "neofetch"
    "plantuml" "graphviz"
    "make" "cmake"
    "tree"
)

sudo pacman -S --needed ${packages[@]}
