#!/usr/bin/env bash

packages=(
    "rustup"
    "gcc"
)

# only require sudo if we need new packages
packages=$(comm -13 <(pacman -Qq | sort) <(printf '%s\n' "${packages[@]}" | sort))
if [ -n "$packages" ]; then
    sudo pacman -S --needed $packages
fi

rustup default stable # default toolchain
rustup target add x86_64-pc-windows-gnu # Windows / libc

# Freescale e500v2 target (nightly so we can `-Z build-std`)
rustup toolchain install nightly
rustup +nightly component add rust-src
# rustup +nightly target add powerpc-unknown-linux-gnuspe # no pre-built rust-std
