#!/bin/bash
# ~/.bash_profile: executed by bash(1) for login shells.

# include .bashrc
if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi

# set PATH to include private bin
if [ -d ~/bin ]; then
    PATH="$HOME/bin:$PATH"
fi

